### PR TITLE
fix(cli): do not generated sh:in for xsd:int dimension

### LINKED ISSUE #570: Dimensions with "int" datatype are missing min/maxInclusive in shape
Instead they have a list of values in the `in` constraint.

See https://s.zazuko.com/uNnLu

I would expect them to behave the same as the "decimal" dimensions.

Sidenote: The dimension has datatype "http://www.w3.org/2001/XMLSchema#int" but the individual values have "http://www.w3.org/2001/XMLSchema#integer" when queried with https://github.com/zazuko/rdf-cube-view-query

### PR DESCRIPTION
**Pull request by tpluscode**
closes #570

### CODE REVIEW

File: cli/lib/toCubeShape/Dimension.js [hunk 1]
```diff
@@ -1,26 +1,31 @@
...
+    case ns.xsd.double.value:
+    case ns.xsd.float.value:
+    case ns.xsd.decimal.value:
+      return term => parseFloat(term.value)
+    case ns.xsd.integer.value:
+    case ns.xsd.int.value:
+    case ns.xsd.gYear.value:
+      return term => parseInt(term.value)
+  }
+}
```
Comment (tpluscode) [inline cli/lib/toCubeShape/Dimension.js:19]: I suppose implemented like this is a little easier on the eye and similar in performance. Could improve by memorising the individual cases or changing them into contents.

By the way, do we want to include other `xsd:integer` subtypes and `xsd:dateTime` here too? @bergos

File: cli/lib/toCubeShape/Dimension.js [hunk 2]
```diff
@@ -1,26 +1,31 @@
...
+    case ns.xsd.date.value:
+      return term => new Date(term.value)
+    case ns.xsd.double.value:
+    case ns.xsd.float.value:
+    case ns.xsd.decimal.value:
+      return term => parseFloat(term.value)
+    case ns.xsd.integer.value:
+    case ns.xsd.int.value:
+    case ns.xsd.gYear.value:
+      return term => parseInt(term.value)
```
Comment (herrstucki) [inline cli/lib/toCubeShape/Dimension.js:17]: @tpluscode Not sure if RDF integers/years can start with 0 but just in case they can, it's usually safer to specify the radix explicitly:

```suggestion
      return term => parseInt(term.value, 10)
```

Comment (tpluscode) [reply cli/lib/toCubeShape/Dimension.js:17]: When will it make a difference?

Comment (herrstucki) [reply cli/lib/toCubeShape/Dimension.js:17]: It used to be a problem because JS would interpret something like `parseInt("010")` as octal instead of decimal. But actually I'm not sure if this is still the case.

https://stackoverflow.com/questions/6611824/why-do-we-need-to-use-radix-parameter-when-calling-parseint

Comment (tpluscode) [reply cli/lib/toCubeShape/Dimension.js:17]: I see. MDN mentions that this should be the case when `radix = 0` but it won't hurt to make it explicit an be sure 👌
