### PR TITLE
fix(ui): display CSV source error

### LINKED ISSUE #280: No error message in case of malformed CSV
I uploaded a CSV having a valid comma seperated header but was semicolon seperated below. In this case (and in other tests too) the CSV Mapper doesn't display an error message, shows the table but not a single column

- [MalformedCsv.zip](https://github.com/zazuko/cube-creator/files/5643185/MalformedCsv.zip)
- https://pipelines-test.lindas.admin.ch/app/cube-projects/cube-project!!zmoke-test-issue-280-zklb72wj8mq/csv-mapping

### PR DESCRIPTION
**Pull request by martinmaillard**
Fixes #280

### CODE REVIEW

File: ui/src/store/serializers.ts [hunk 1]
```diff
@@ -20,6 +20,7 @@ export function serializeSource (source: CsvSource): CsvSource {
   return Object.freeze({
     ...serializeResource(source),
     name: source.name,
+    error: source.error,
```
Comment (lucafurrer) [inline ui/src/store/serializers.ts:23]: I missed this one :wink:

**Review by lucafurrer — APPROVED** [review]
