### PR TITLE
fix: identifier mapping column replacement

### LINKED ISSUE #311: CSV Mapping: Link to table doesn't work (differient column names)
Steps to reproduce
- Map all columns of LinkedTables2_Gaeste.csv from [LinkedTables.zip](https://github.com/zazuko/cube-creator/files/5665129/LinkedTables.zip)
  - Set Identifier Template to `{Vorname}`
- Map only "Getraenk" and "Anzahl" in LinkedTables1_Observation.csv from [LinkedTables.zip](https://github.com/zazuko/cube-creator/files/5665129/LinkedTables.zip) (as observation table)
- Link `Gast` from observation table to Gaeste-Table
- Run pipeline
  - Bug: All rows have the same (wrong) "Gast"-Mapping

### PR DESCRIPTION
**Pull request by martinmaillard**
CsvColumn is not a resource...

Fixes #311

### CODE REVIEW

**Comment by martinmaillard** [comment]
e2e tests are passing locally...

File: apis/core/lib/csvw-builder/index.ts [hunk 1]
```diff
@@ -48,22 +48,36 @@ function mappedLiteralColumn({ csvMapping, columnMapping, column }: CsvwBuilding
...
+  }
+
+  if (!referencedTable.csvSource) {
+    throw new Error(`Table ${columnMapping.referencedTable.id} not linked to a source`)
+  }
+
+  const referencedSource = await resources.getResource<CsvSource>(referencedTable.csvSource.id)
+  if (!referencedSource) {
+    throw new Error(`Source ${referencedTable.csvSource.id} not found`)
+  }
```
Comment (tpluscode) [inline apis/core/lib/csvw-builder/index.ts:68]: If you rebase now you'll be able to remove the throw

```suggestion
  const referencedTable = await resources.getResource<Table>(columnMapping.referencedTable.id)

  if (!referencedTable.csvSource) {
    throw new Error(`Table ${columnMapping.referencedTable.id} not linked to a source`)
  }

  const referencedSource = await resources.getResource<CsvSource>(referencedTable.csvSource.id)
```

**Review by lucafurrer — APPROVED** [review]

**Comment by lucafurrer** [comment]
> e2e tests are passing locally...

Strange, can it be that there is a problem with the s3-container?
