### PR TITLE
fix(ui): previous jobs not displayed on deployed instance

### LINKED ISSUE #291: Previous jobs are not displayed in test/int
The feature is working locally.

### PR DESCRIPTION
**Pull request by martinmaillard**
Fixes #291

### CODE REVIEW

File: ui/src/store/serializers.ts [hunk 1]
```diff
@@ -111,14 +123,16 @@ export function serializeDimensionMetadata (dimension: DimensionMetadata): Dimen
 }
 
 export function serializeJobCollection (collection: JobCollection): JobCollection {
+  const members = (collection as any)[hydra.member.value] ?? [] as Job[]
```
Comment (tpluscode) [inline ui/src/store/serializers.ts:126]:
```suggestion
  const members = collection.getArray<Job>(hydra.member)
```

**Review by tpluscode — APPROVED** [review]
